name: ui

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:

env:
  REPOSITORY_MAIN_BRANCH: "master"
  DOCKER_IMAGE_REPOSITORY: mintproject
  DOCKER_IMAGE_NAME: mic-web
  DOCKER_FILE: ".Dockerfile-actions"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build (webpack)
        run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: ./build/
          retention-days: 1

  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: nextjs-build
          path: build/

      - name: Create environment variable with the commit id
        run: |
          echo "DOCKER_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Expose the commit id
        id: exposeValue
        run: |
          echo "::set-output name=docker_tag::${{ env.DOCKER_TAG }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          context: .
          tags: ${{ env.DOCKER_IMAGE_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.branch-name.outputs.current_branch }}, ${{ env.DOCKER_IMAGE_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
          file: ${{ env.DOCKER_FILE}}

      - name: Running on the default branch.
        if: steps.branch-name.outputs.is_default == 'true'
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          context: .
          tags: ${{ env.DOCKER_IMAGE_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          file: ${{ env.DOCKER_FILE}}
